### PR TITLE
Adding propagation and verbose control

### PR DESCRIPTION
**Pull request by iec989**

### CODE REVIEW

**Review by Juicetan — CHANGES_REQUESTED** [review]
Sorry for the delayed response.  Please add opening and closing braces even for one line if statements.

**Comment by iec989** [comment]
> Sorry for the delayed response. Please add opening and closing braces even for one line if statements.

Done @Juicetan - Sorry, I've been on holidays for a while

**Comment by Juicetan** [comment]
Hello, apologies but I think if i merge this PR it'll overwrite my own README.md

**Comment by Juicetan** [comment]
I added your changes and published to NPM.  Thanks for the suggestions.

**Pull request closed without merging**
